### PR TITLE
fix 5.4.0 regression of 'where' as parameter

### PR DESCRIPTION
**Pull request by Alexsey**
https://github.com/mickhansen/graphql-sequelize/issues/508

### CODE REVIEW

**Comment by mickhansen** [comment]
Mind verifying this fix @RichAyotte?

**Comment by RichAyotte** [comment]
Works good, thanks.

**Comment by Alexsey** [comment]
Sorry for initial breakdown. With graphiql it was not working before 5.4.0. I'll add some docs about both mods in a day or two

**Comment by RichAyotte** [comment]
Only saw a version change in 5.4.1. Too bad this PR didn't make it.

**Comment by mickhansen** [comment]
v5.4.2

Sorry about that, 5.4.1 was just to get ^5  as the latest npm version again

**Comment by RichAyotte** [comment]
Nice, thank you. Having this merged will save me a bit of work this morning.

**Pull request merged**
