### PR TITLE
Added GraphQLJSON type for JSON & JSONB DataTypes

### PR DESCRIPTION
**Pull request by ivnivnch**

### CODE REVIEW

**Comment by bringking** [comment]
Looks like the map function tests are failing -

  1) attributeFields should be possible to rename fields with a object map:
  2) attributeFields should be possible to rename fields with a function that maps keys:
 
Also, IMHO it should be considered if this library should be responsible for providing custom GraphQL types, or just allow users to provide their own mappings via some method like discussed in #126. Interested to hear @mickhansen's thoughts

**Comment by mickhansen** [comment]
@bringking Yeah they're failing on master aswell, not sure why

**Comment by mickhansen** [comment]
I'm not sure about this, a custom JSON scalar might make sense. But most of the time users should probably supply their own custom ObjectType for a JSON field so you still have some sort of schema.

**Comment by ivnivnch** [comment]
This can be useful if the shape of JSON object is changed at runtime. It can be defined in the scheme, but I see it as a helper object is the same as the other helper functions.

**Comment by mickhansen** [comment]
Definitely, i like this as a possible default with the option of letting users owerwrite it both via attributeFields and type mapping.

**Comment by ivnivnch** [comment]
This is possible with exclude/only options for attributeField function.

**Comment by mickhansen** [comment]
I'm aware :)

**Comment by mickhansen** [comment]
Custom JSON scalar was added by @bringking: https://github.com/mickhansen/graphql-sequelize/blob/master/src/types/jsonType.js

**Pull request closed without merging**
