### PR TITLE
Sequelize 4 symbol operators support.

### LINKED ISSUE #585: Support for Symbol operators
String operators have been deprecated in Sequelize since version 4 and they'll be completely dropped in version 5. Would you consider making the minimum Sequelize version to 4 and accept a patch for operator Symbols?

https://github.com/sequelize/sequelize/pull/9278

### PR DESCRIPTION
**Pull request by RichAyotte**
Fixes #585

### CODE REVIEW

**Comment by RichAyotte** [comment]
@mickhansen Let me know if there's anything that you'd like to see improved before merging. Thanks.

**Comment by mickhansen** [comment]
Looks good to me, just haven't been around, have you smoke tested this in your own project @RichAyotte?

**Comment by RichAyotte** [comment]
Yes, it's running with this patch in my project with Sequelize 4.37.10

**Comment by mickhansen** [comment]
v8.1.3

**Pull request merged**
