### PR TITLE
Fix indexOf check for field helper options

### PR DESCRIPTION
**Pull request by Sneagan**
Use the idiomatic method of checking indexOf and by so doing fix false positives on the check.

### CODE REVIEW

**Comment by mickhansen** [comment]
`~` IS idiomatic, if there's a false positive please include a test (it's been working well so far)

**Comment by Sneagan** [comment]
If we must use `~`, I'll submit an alternative solution.

**Comment by mickhansen** [comment]
@Sneagan We musn't necessarily, if you provide a test case where it fails i'm happy to merge your fix :)

**Comment by Sneagan** [comment]
I'll update it with a test, but there is and *existing failing test* that is the result of a tilde in the test. These tildes are out of control.

**Pull request closed without merging**
