### PR TITLE
chore: test Node.js 6, 8 and 10

### PR DESCRIPTION
**Pull request by DanielRuf**

### CODE REVIEW

**Comment by DanielRuf** [comment]
This should not have been merged yet.

We have to fix the unit tests and dependencies first.

**Comment by DanielRuf** [comment]
https://travis-ci.org/mickhansen/graphql-sequelize/builds/380592565

**Comment by mickhansen** [comment]
Ah my bad, i assumed it would just work on the future dialects actually.

**Comment by mickhansen** [comment]
Having the sqlite package in there at all is a bit of legacy i guess, don't really test against it anymore.

**Comment by DanielRuf** [comment]
> Having the sqlite package in there at all is a bit of legacy i guess, don't really test against it anymore.

```shell
mocha $npm_package_options_mocha test/unit/*.test.js test/unit/**/*.test.js

/Users/druf/projects/graphql-sequelize/node_modules/sequelize/lib/dialects/sqlite/connection-manager.js:25
      throw new Error('Please install sqlite3 package manually');
      ^

Error: Please install sqlite3 package manually
    at new ConnectionManager (/Users/druf/projects/graphql-sequelize/node_modules/sequelize/lib/dialects/sqlite/connection-manager.js:25:13)
```

**Comment by mickhansen** [comment]
Hmm, that's odd for a unit test. Thanks for the fixes @DanielRuf

**Pull request merged**
