### PR TITLE
fix order

### PR DESCRIPTION
**Pull request by alichherawalla**
Hi, 

Thank you for this amazing library. We use it extensively and has helped solve a lot of our problems and increase velocity. 

However we identified that order doesn't work when using sequelize instead of dataloader-sequelize. Adding in this change fixes it, else it always defaults to ["id", "asc"] for the order.

### CODE REVIEW

**Comment by mickhansen** [comment]
How does your code look that you are passing `options.order`? To my knowledge `createConnectionResolver` / `createConnection` do not take these, are you modifying in a hook?

**Comment by alichherawalla** [comment]
Hi, apologies for the delay in response. 

I get order since I use `defaultListArgs`

**Comment by alichherawalla** [comment]
Hi @mickhansen, 

Possible to please get a review?

**Comment by mickhansen** [comment]
HI @alichherawalla, sorry about the delay, could you add a test to guard against regression?

**Comment by alichherawalla** [comment]
Hi, 

Just saw this. Yes will add it in @mickhansen

**Pull request closed without merging**
