### PR TITLE
Support `where` option from arguments, by parsing JSON arguments in s…

### PR DESCRIPTION
**Pull request by JohnyDays**
Where option wasn't actually working in my case, had to make this change to the argument parsing.

Cheers

### CODE REVIEW

**Comment by mickhansen** [comment]
Please add a test aswell

**Comment by JohnyDays** [comment]
Added a test and squashed 👍

**Comment by mickhansen** [comment]
v2.1.1

**Comment by JohnyDays** [comment]
Thanks

**Pull request merged**
