### PR TITLE
add support for uuidv4 data type

### LINKED ISSUE #690: Support UUIDV4 data type
```
Error: Unable to convert UUIDV4 to a GraphQL type
    at Object.toGraphQL (/app/node_modules/graphql-sequelize/lib/typeMapper.js:112:9)
    at /app/node_modules/graphql-sequelize/lib/defaultArgs.js:24:27
    at Array.forEach (<anonymous>)
    at module.exports (/app/node_modules/graphql-sequelize/lib/defaultArgs.js:21:10)
    at /app/node_modules/sequelize-graphql-schema/dist/sequelize-graphql-schema.js:610:31
    at Array.reduce (<anonymous>)
    at generateQueryRootType (/app/node_modules/sequelize-graphql-schema/dist/sequelize-graphql-schema.js:594:43)
    at generateSchema (/app/node_modules/sequelize-graphql-schema/dist/sequelize-graphql-schema.js:898:14)
    at Object.<anonymous> (/app/server.js:7:34)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11
```

### PR DESCRIPTION
**Pull request by realies**
should fix #690

### CODE REVIEW

**Comment by realies** [comment]
sup with the postgres failure?

**Comment by mickhansen** [comment]
Usually uuid is used as primary key which should be converted to GraphQLID, do you have non primary key uuid fields?

**Comment by mickhansen** [comment]
v9.4.0

**Comment by realies** [comment]
@mickhansen, seems like `DataTypes.UUIDV4` is only used for the `defaultValue` field parameter and not `type`. Feel free to revert.

**Comment by mickhansen** [comment]
@realies ah yeah right, oh wel, no harm here

**Pull request merged**
