### PR TITLE
chore(package): update graphql to version 0.8.2

### PR DESCRIPTION
**Pull request by dervos**
https://github.com/graphql/graphql-js/releases/tag/v0.8.0

### CODE REVIEW

**Comment by mickhansen** [comment]
Ah, wanted you to open without the graphql update since it conflicts with express-graphql and graphql-relay

**Comment by dervos** [comment]
@mickhansen Ah I understand now. Sorry for the misunderstanding, I'm new to this.

**Comment by dervos** [comment]
It seems the tests have passed after I ran them again. Tests also passed on my local machine.

However it failed the first time when I pushed the last time. Any reason for this inconsistency?

**Comment by mickhansen** [comment]
Some tests fail because of ordering that isn't always deteministic, never got around to fixing it.

**Comment by mickhansen** [comment]
v4.0.4

**Pull request merged**
