### PR TITLE
Enhancement: Resolver option `defaultAttributes`

### PR DESCRIPTION
**Pull request by jonathanewerner**
As discussed in #172, i've implemented the resolver option `defaultAttributes`.

I also fixed the flakyness issue in `resolver.test.js` by not asserting on the order of the compared arrays in two cases.

I wasn't entirely sure about some code style issues that are not answered by the `.eslintrc`:
- `var foo = require('...') vs `import ...`
- `const` vs. `var`?
- arrow fn callbacks vs. `function()`?
- use of es2015/16 features like destructuring -- which ones are "allowed" / which node version is targeted?

It might be a good idea to provide more strict guidance per `.eslintrc`for a more homogenous code look and feel -- I spent the majority of time thinking about those issues and how to "fit in" to the existing code style(s). :)

### CODE REVIEW

**Comment by mickhansen** [comment]
`import`
`const`
arrow when you need the context, otherwise function
whatever es6 you like, we use babel

you're welcome to update .eslintrc

**Comment by jonathanewerner** [comment]
Ok, great, I'll add some rules to `.eslintrc` then. I'll also create a small `CONTRIBUTING.md` guide with some setup & general advice if you don't mind, just as a starting point. I'll do this in another PR though, this one is finished from my side.

**Comment by mickhansen** [comment]
LGTM, i would appreciate a squash to a few more descriptive commits.

**Comment by jonathanewerner** [comment]
Will do.

**Comment by jonathanewerner** [comment]
I squashed it.

**Comment by mickhansen** [comment]
`v0.22.0`

**Pull request merged**
