### PR TITLE
adding sql lite for the counts

### PR DESCRIPTION
**Pull request by corbanb**
allow counts for sqlite queries. 

this will help with test runners using sqlite

### CODE REVIEW

**Comment by corbanb** [comment]
anyone know what I need to do for the tests to use sqlite? also not sure why this would even fail if its not running sqlite in the test suite 👎

**Comment by mickhansen** [comment]
Failure is unrelated, there's a wonky non-deterministic test that fails here and there.

**Comment by mickhansen** [comment]
Ill merge this but just keep in mind this library does not support sqlite specifically.

**Comment by mickhansen** [comment]
v9.3.4

**Pull request merged**
