### PR TITLE
renamed fieldASTs to fieldNodes

### LINKED ISSUE #369: sequelizeConnection breaks with latest version of graphql
sequelizeConnection breaks with latest version of graphql (0.8) with error

```
Cannot read property '0' of undefined
```. 

Most probably due to these breaking changes:
https://github.com/graphql/graphql-js/releases/tag/v0.8.0

### PR DESCRIPTION
**Pull request by dervos**
fixes #369 

see https://github.com/graphql/graphql-js/releases/tag/v0.8.0

### CODE REVIEW

**Comment by legomind** [comment]
This change needs to be backwards compatible with older versions of graphql-js

**Comment by mickhansen** [comment]
@dervos please change the code so it supports looking for both keys.

**Comment by mickhansen** [comment]
You might want to target master with this fix instead as graphql-relay does not appear to be too happy with the new graphql

**Comment by dervos** [comment]
@mickhansen does this workaround satisfy the need for backwards compatibility?

The build fails on this branch but succeeds on [mine](https://travis-ci.org/dervos/graphql-sequelize/jobs/179709073), perhaps you could re-run it?

**Comment by mickhansen** [comment]
@dervos It does, but you'll need to open against master as there are dependency conflicts.

**Pull request closed without merging**
