### PR TITLE
fix(defaultArgs): support compound primary keys

### LINKED ISSUE #592: Support compound primary key in defaultArgs
Looking at `defaultArgs`, it's obvious that it doesn't support compound primary keys.

### PR DESCRIPTION
**Pull request by jedwards1211**
fix #592

### CODE REVIEW

**Comment by jedwards1211** [comment]
Seems like a transient CI test failure:
```
  1 failing
  1) relay should support after queries on connections:
      AssertionError: expected '0.0244309377324734' to equal '0.10437318821810226'
      + expected - actual
      -0.0244309377324734
      +0.10437318821810226
```

**Comment by mickhansen** [comment]
That failure is transient. But please add a new test covering this usecase.

**Comment by jedwards1211** [comment]
@mickhansen okay I added a test.  Btw, is there any reason you're not linting the test files?

**Comment by jedwards1211** [comment]
@mickhansen transient failure again

**Comment by mickhansen** [comment]
> @mickhansen okay I added a test. Btw, is there any reason you're not linting the test files?

No real reason, habit i guess.

**Pull request merged**
